-- MockMentor Database Schema

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    domain TEXT NOT NULL
);

-- Interview Sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY, -- UUID generated by API
    user_id INTEGER NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    mode TEXT CHECK(mode IN ('FULL', 'BEHAVIORAL', 'TECHNICAL')),
    jd_text TEXT NOT NULL,
    resume_text TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

-- Questions & Evaluation History
CREATE TABLE IF NOT EXISTS questions_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT,
    score INTEGER, -- 1 to 10
    feedback TEXT,
    weaknesses TEXT, -- Comma-separated or JSON list of topics identified
    FOREIGN KEY(session_id) REFERENCES sessions(id)
);

-- Persistent Memory / Candidate Weakspots Profile
CREATE TABLE IF NOT EXISTS weakspots (
    user_id INTEGER NOT NULL,
    topic TEXT NOT NULL,
    rating INTEGER NOT NULL DEFAULT 5, -- 1 (very weak) to 10 (fully mastered)
    times_tested INTEGER DEFAULT 1,
    last_tested_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id, topic),
    FOREIGN KEY(user_id) REFERENCES users(id)
);
